import { isDraftSeason } from '@packages/dates/utils';
import { getSession } from '@packages/nextjs/session/getSession';
import { getPlatform } from '@packages/utils/platform';
import { DateTime } from 'luxon';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

import { isAirdropLive } from './lib/airdrop/checkAirdropDates';

// These are the links that are only accessible to logged in users
const privateLinks = ['/profile', '/notifications', '/welcome', '/claim', '/builders-you-know', '/quests', '/accounts'];
const disabledDraftLinks = ['/scout', '/developers', '/profile/projects'];

// Previous middleware logic (before December 22, 2025)
async function previousMiddlewareLogic(request: NextRequest) {
  const session = await getSession();
  const isLoggedIn = !!session.scoutId;
  const path = request.nextUrl.pathname;
  const response = NextResponse.next();
  const platform = getPlatform();
  const draftSeason = isDraftSeason();
  const airdropLive = isAirdropLive();

  if (path === '/taiko') {
    return NextResponse.redirect(new URL('/info/partner-rewards/taiko', request.url));
  }

  if (path === '/gooddollar') {
    return NextResponse.redirect(new URL('/info/partner-rewards/gooddollar', request.url));
  }

  if (path === '/quests') {
    return NextResponse.redirect(new URL('/scout', request.url));
  }

  if (draftSeason) {
    if ((path === '/airdrop' && !airdropLive) || path.startsWith('/u/')) {
      return NextResponse.redirect(new URL(isLoggedIn ? '/draft/register' : '/draft', request.url));
    }

    if (disabledDraftLinks.some((link) => path.startsWith(link))) {
      return NextResponse.redirect(new URL(isLoggedIn ? '/draft/register' : '/draft', request.url));
    }

    return response;
  }

  if (path.startsWith('/draft')) {
    return NextResponse.redirect(new URL('/scout', request.url));
  }

  if (!isLoggedIn && path !== '/home' && platform === 'telegram') {
    // eslint-disable-next-line no-console
    console.log(`Redirecting to telegram loading screen`, { path, platform, ...session });
    return NextResponse.redirect(new URL('/home', request.url));
  }

  // Redirect to login if anonymous user clicks on private links
  if (!isLoggedIn && privateLinks.some((link) => path.startsWith(link))) {
    // eslint-disable-next-line no-console
    console.log('Redirecting to login', { path, platform, ...session });
    return NextResponse.redirect(new URL('/login', request.url));
  }

  // Redirect to home if logged in user clicks on login
  if (isLoggedIn && (path === '/login' || path === '/' || path === '/home')) {
    // eslint-disable-next-line no-console
    console.log('Redirecting to scout page', { path, platform, session });
    return NextResponse.redirect(new URL('/scout', request.url));
  }

  return response;
}

// New middleware logic (from December 22, 2025 onwards)
async function newMiddlewareLogic(request: NextRequest) {
  const session = await getSession();
  const isLoggedIn = !!session.scoutId;
  const path = request.nextUrl.pathname;

  // List of pages that should be accessible without authentication
  const publicPages = ['/login', '/info'];
  const isPublicPage = publicPages.some((page) => path.startsWith(page));

  // Redirect unauthenticated users to /login (except for public pages)
  if (!isLoggedIn && !isPublicPage) {
    return NextResponse.redirect(new URL('/login', request.url));
  }

  // Redirect authenticated users to /claim (except for /airdrop and /claim itself)
  if (
    isLoggedIn &&
    path !== '/claim' &&
    path !== '/airdrop' &&
    !path.startsWith('/claim/') &&
    !path.startsWith('/airdrop/')
  ) {
    return NextResponse.redirect(new URL('/claim', request.url));
  }

  return NextResponse.next();
}

export async function middleware(request: NextRequest) {
  // Switch to new logic from Monday December 22, 2025 00:00 UTC onwards
  const enableDate = DateTime.fromObject(
    { year: 2025, month: 12, day: 22, hour: 0, minute: 0, second: 0 },
    { zone: 'utc' }
  );

  const currentTime = DateTime.utc();

  // Use new logic if current time is on or after the enable date
  if (currentTime >= enableDate) {
    return newMiddlewareLogic(request);
  }

  // Otherwise use previous logic
  return previousMiddlewareLogic(request);
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - images (image files)
     * - favicon.ico (favicon file)
     * - robots.txt (indexing file generated by nextjs)
     * - __ENV.js (file to handle env public variables)
     * - manifest.webmanifest (manifest created by nextjs)
     * - sw.js (service worker)
     * - fonts (font files)
     */
    '/((?!api|_next/static|_next/image|images|favicon.ico|robots.txt|__ENV.js|manifest.webmanifest|sw.js|fonts).*)'
  ]
};
