services:
  defaults:
    image: '310849459438.dkr.ecr.us-east-1.amazonaws.com/${IMGNAME}:${IMGTAG}'
    labels:
      com.datadoghq.ad.logs: '[{"source": "nodejs", "service": "${SERVICE_NAME}", "version": "${IMGTAG}"}]'
      com.datadoghq.tags.env: '${SERVICE_ENV:-tst}'
      com.datadoghq.tags.service: '${SERVICE_NAME}'
      com.datadoghq.tags.version: '${IMGTAG}'
    env_file:
      - '.env'
    environment:
      - NODE_ENV=production
    profiles:
      # services need at least one profile or else they will be started along with what is in COMPOSE_PROFILES env var
      - default_config

  prd-scoutgame:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npm run prisma:deploy && npx react-env --path .env --dest ./apps/scoutgame/public -- node --max-old-space-size=8192 --require dd-trace/init node_modules/.bin/next start apps/scoutgame --keepAliveTimeout 70000'
      ]
    profiles:
      - prd-scoutgame

  stg-scoutgame:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npm run prisma:deploy && npx react-env --path .env --dest ./apps/scoutgame/public -- node --max-old-space-size=8192 --require dd-trace/init node_modules/.bin/next start  apps/scoutgame --keepAliveTimeout 70000'
      ]
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-scoutgame

  prd-onchain-scoutgame:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npm run prisma:deploy && npx react-env --path .env --dest ./apps/scoutgame/public -- node --max-old-space-size=8192 --require dd-trace/init node_modules/.bin/next start apps/scoutgame --keepAliveTimeout 70000'
      ]
    profiles:
      - prd-onchain-scoutgame

  stg-onchain-scoutgame:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npm run prisma:deploy && npx react-env --path .env --dest ./apps/scoutgame/public -- node --max-old-space-size=8192 --require dd-trace/init node_modules/.bin/next start  apps/scoutgame --keepAliveTimeout 70000'
      ]
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-onchain-scoutgame

  prd-agents:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['npm', 'run', 'agents:prod']
    profiles:
      - prd-agents

  stg-agents:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['npm', 'run', 'agents:staging']
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-agents

  prd-scoutgamecron:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['npm', 'run', 'cron:prod']
    profiles:
      - prd-scoutgamecron

  stg-scoutgamecron:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['npm', 'run', 'cron:staging']
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-scoutgamecron

  prd-onchain-scoutgamecron:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['npm', 'run', 'cron:prod']
    profiles:
      - prd-onchain-scoutgamecron

  stg-onchain-scoutgamecron:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['npm', 'run', 'cron:staging']
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-onchain-scoutgamecron

  prd-scoutgameadmin:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['sh', '-c', 'node_modules/.bin/next start apps/admin --keepAliveTimeout 70000']
    profiles:
      - prd-scoutgameadmin

  stg-scoutgameadmin:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['sh', '-c', 'node_modules/.bin/next start apps/admin --keepAliveTimeout 70000']
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-scoutgameadmin

  prd-scoutgame-draft:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npx react-env --path .env --dest ./apps/draft/public -- node --max-old-space-size=8192 --require dd-trace/init node_modules/.bin/next start apps/draft --keepAliveTimeout 70000'
      ]
    profiles:
      - prd-scoutgame-draft

  stg-scoutgame-draft:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npm run prisma:deploy && npx react-env --path .env --dest ./apps/draft/public -- node --max-old-space-size=8192 --require dd-trace/init node_modules/.bin/next start  apps/draft --keepAliveTimeout 70000'
      ]
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-scoutgame-draft

  prd-scoutgametelegram:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npx react-env --path .env --dest ./apps/scoutgame/public -- node --max-old-space-size=8192 --require dd-trace/init node_modules/.bin/next start apps/scoutgame --keepAliveTimeout 70000'
      ]
    profiles:
      - prd-scoutgametelegram

  stg-scoutgametelegram:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npm run prisma:deploy && npx react-env --path .env --dest ./apps/scoutgame/public -- node --max-old-space-size=8192 --require dd-trace/init node_modules/.bin/next start  apps/scoutgame --keepAliveTimeout 70000'
      ]
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-scoutgametelegram

  devapp:
    build:
      context: .
    ports:
      - '80:3000'
    command: ['npm', 'start']
    volumes:
      - $PWD:/app
    env_file:
      - '.env'
    depends_on:
      - localpostgres
    profiles:
      - dev

  localpostgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ${LOCAL_DATA_DIR:-/home/postgresql}:/var/lib/postgresql/
    profiles:
      - dev

  datadog-agent:
    image: public.ecr.aws/datadog/agent
    hostname: datadog-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/host/var/log:ro
    ports:
      - '8125:8125/udp'
      - '8126:8126/tcp'
    env_file:
      - '.env'
    environment:
      DD_LOGS_ENABLED: 'true'
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: 'true'
      DD_CONTAINER_EXCLUDE: 'image:public.ecr.aws/datadog/agent'
      DD_SITE: 'datadoghq.com'
      DD_APM_ENABLED: 'true'
      DD_APM_NON_LOCAL_TRAFFIC: 'true'
      DD_ENV: '${SERVICE_ENV:-tst}'
      DD_SERVICE: '${SERVICE_NAME}'
      DD_USE_DOGSTATSD: 'true'
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: 'true'
      DD_EC2_PREFER_IMDSV2: 'true'
    profiles:
      - prd-scoutgame
      - prd-scoutgameadmin
      - prd-scoutgamecron
      - prd-onchain-scoutgame
      - prd-onchain-scoutgamecron
      - prd-scoutgametelegram
      - ddtst
