services:
  defaults:
    image: '310849459438.dkr.ecr.us-east-1.amazonaws.com/${IMGNAME}:${IMGTAG}'
    env_file:
      - '.env'
    environment:
      - NODE_ENV=production
    profiles:
      # services need at least one profile or else they will be started along with what is in COMPOSE_PROFILES env var
      - default_config

  prd-scoutgame:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npm run prisma:deploy && npx react-env --path .env --dest ./apps/scoutgame/public -- node --max-old-space-size=8192 --require dd-trace/init node_modules/.bin/next start apps/scoutgame --keepAliveTimeout 70000'
      ]
    profiles:
      - prd-scoutgame

  stg-scoutgame:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npx react-env --path .env --dest ./apps/scoutgame/public -- node_modules/.bin/next start apps/scoutgame --keepAliveTimeout 70000'
      ]
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-scoutgame

  prd-agents:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['npm', 'run', 'agents:prod']
    profiles:
      - prd-agents

  stg-agents:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['npm', 'run', 'agents:staging']
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-agents

  prd-scoutgamecron:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['npm', 'run', 'cron:prod']
    profiles:
      - prd-scoutgamecron

  stg-scoutgamecron:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['npm', 'run', 'cron:staging']
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-scoutgamecron

  prd-scoutgameadmin:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['sh', '-c', 'node_modules/.bin/next start apps/admin --keepAliveTimeout 70000']
    profiles:
      - prd-scoutgameadmin

  stg-scoutgameadmin:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command: ['sh', '-c', 'node_modules/.bin/next start apps/admin --keepAliveTimeout 70000']
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-scoutgameadmin

  prd-scoutgametelegram:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npx react-env --path .env --dest ./apps/scoutgame/public -- node --max-old-space-size=8192 --require dd-trace/init node_modules/.bin/next start apps/scoutgame --keepAliveTimeout 70000'
      ]
    profiles:
      - prd-scoutgametelegram

  stg-scoutgametelegram:
    extends:
      service: defaults
    ports:
      - '80:3000'
    command:
      [
        'sh',
        '-c',
        'npm run prisma:deploy && npx react-env --path .env --dest ./apps/scoutgame/public -- node --max-old-space-size=8192 --require dd-trace/init node_modules/.bin/next start  apps/scoutgame --keepAliveTimeout 70000'
      ]
    environment:
      - REACT_APP_APP_ENV=staging
    profiles:
      - stg-scoutgametelegram

  devapp:
    build:
      context: .
    ports:
      - '80:3000'
    command: ['npm', 'start']
    volumes:
      - $PWD:/app
    env_file:
      - '.env'
    depends_on:
      - localpostgres
    profiles:
      - dev

  localpostgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ${LOCAL_DATA_DIR:-/home/postgresql}:/var/lib/postgresql/
    profiles:
      - dev
