export const SCOUT_AGENT_BUILDER_TELEGRAM_BOT_TOKEN = process.env.SCOUT_AGENT_BUILDER_TELEGRAM_BOT_TOKEN as string;

export const SCOUT_AGENT_BUILDER_OPENAI_API_KEY = process.env.SCOUT_AGENT_BUILDER_OPENAI_API_KEY as string;
